"""
TripReady Localization Generator
---------------------------------
Usage: python lib/l10n/generate_localizations.py

Reads all app_XX.arb files in lib/l10n/ and writes
lib/l10n/app_localizations.dart with a class per language.

To add a new language:
  1. Create lib/l10n/app_XX.arb (copy app_en.arb, translate values)
  2. Run this script
  3. Add Locale('xx') to LanguageService.supportedLocales
  4. Add the language to the Settings dropdown
"""

import json, re, os, glob

script_dir = os.path.dirname(os.path.abspath(__file__))
arb_files = glob.glob(os.path.join(script_dir, 'app_??.arb'))

if not arb_files:
    print("No ARB files found in", script_dir)
    exit(1)

# Load English as base
en_path = os.path.join(script_dir, 'app_en.arb')
en = json.load(open(en_path, encoding='utf-8'))
keys = [k for k in en if not k.startswith('@')]
meta = {k[1:]: v for k, v in en.items() if k.startswith('@')}

def get_placeholders(key):
    m = meta.get(key, {})
    return m.get('placeholders', {}) if isinstance(m, dict) else {}

def ds(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n')

def interpolate(val, placeholders):
    result = ds(val)
    for pname in placeholders:
        result = result.replace('{' + pname + '}', "' + " + pname + ".toString() + '")
    result = result.replace(" + ''", "")
    return result

def param_type(v):
    return 'int' if isinstance(v, dict) and v.get('type') == 'int' else 'String'

getter_keys = [k for k in keys if not get_placeholders(k)]
method_keys = [k for k in keys if get_placeholders(k)]

# Abstract members
abstract_members = []
for k in getter_keys:
    abstract_members.append(f'  String get {k};')
for k in method_keys:
    ph = get_placeholders(k)
    params = ', '.join(f'{param_type(v)} {n}' for n, v in ph.items())
    abstract_members.append(f'  String {k}({params});')

# Load all locales
locales = {}
for path in sorted(arb_files):
    code = os.path.basename(path)[4:6]  # app_fr.arb -> fr
    locales[code] = json.load(open(path, encoding='utf-8'))

# Generate implementation per locale
locale_classes = []
for code, data in locales.items():
    class_name = f'_AppLocalizations{code.capitalize()}'
    members = []
    for k in getter_keys:
        val = data.get(k, en.get(k, k))
        members.append(f"  @override\n  String get {k} => '{ds(val)}';")
    for k in method_keys:
        ph = get_placeholders(k)
        params = ', '.join(f'{param_type(v)} {n}' for n, v in ph.items())
        val = data.get(k, en.get(k, k))
        body = interpolate(val, ph)
        members.append(f"  @override\n  String {k}({params}) => '{body}';")

    locale_classes.append(
        f"// ── {code.upper()} ────────────────────────────────────────────────────\n"
        f"class {class_name} extends AppLocalizations {{\n"
        f"  {class_name}() : super('{code}');\n"
        + '\n'.join(members)
        + '\n}'
    )

# Delegate load() cases
load_cases = '\n'.join(
    f"      case '{code}': return _AppLocalizations{code.capitalize()}();"
    for code in locales
)
supported = ', '.join(f"Locale('{code}')" for code in locales)
is_supported = ', '.join(f"'{code}'" for code in locales)

dart = f'''// ignore_for_file: type=lint
// GENERATED BY lib/l10n/generate_localizations.py — DO NOT EDIT MANUALLY
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

abstract class AppLocalizations {{
  AppLocalizations(this.localeName);
  final String localeName;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = [{supported}];

{chr(10).join(abstract_members)}
}}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {{
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale l) => [{is_supported}].contains(l.languageCode);
  @override
  Future<AppLocalizations> load(Locale l) async {{
    switch (l.languageCode) {{
{load_cases}
      default: return _AppLocalizationsEn();
    }}
  }}
  @override
  bool shouldReload(_) => false;
}}

{chr(10).join(locale_classes)}
'''

out_path = os.path.join(script_dir, 'app_localizations.dart')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(dart)

print(f"Done. {len(keys)} keys, {len(locales)} language(s): {', '.join(locales.keys())}")
print(f"Written to: {out_path}")
